#!/bin/sh

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
    # Fall back to using the very slow lsb_release utility
    DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

# Define Colors
BLACK='\033[0;30m'
GRAY='\033[1;30m'
LIGHT_GRAY='\033[0;37m'
WHITE='\033[1;37m'
RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
GREEN='\033[0;32m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[0;33m'
LIGHT_YELLOW='\033[1;33m'
BLUE='\033[0;34m'
LIGHT_BLUE='\033[1;34m'
MAGENTA='\033[0;35m'
LIGHT_MAGENTA='\033[1;35m'
CYAN='\033[0;36m'
LIGHT_CYAN='\033[1;36m'				        
NO_COLOR='\033[0m'

# Default Colors
DC="${NO_COLOR}"

KERNEL=`uname -r`
OPERATING_SYSTEM=`uname -o`
IPADDR=$(ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}')
EXTIPADDR=`dig +short myip.opendns.com @resolver1.opendns.com`
ISP=`geoiplookup ${EXTIPADDR} |grep ASN|cut -d: -f2`
UPTIME=`uptime |cut -d, -f-2|cut -d\  -f4-`
#UPTIME=`awk '{print int($1/86400)" day(s) "int($1%86400/3600)":"int(($1%3600)/60)":`
UPRECORDS=`uprecords| grep -e "->   1"|cut -d\| -f1|cut -d\  -f9-`

LOAD=`cat /proc/loadavg | awk '{print $1}'`
DISK=`df -h / | awk '{ a = $2 } END { print a }'`
DISKUSED=`df -h / | awk '{ a = $3 } END { print a }'`
DISKFREE=`df -h / | awk '{ a = $4 } END { print a }'`
DISKPER=`df -h / | awk '/\// {print $(NF-1)}'`
MEMORY=`free -gh --si | head -n 2 | tail -n 1 | awk {'print $2'}`
MEMUSED=`free -gh --si | head -n 2 | tail -n 1 | awk {'print $3'}`
MEMFREE=`free -gh --si | head -n 2 | tail -n 1 | awk {'print $4'}`
MEMPER=`free -gh --si | awk '/Mem/ { printf("%3.1f%%", $3/$2*100) }'`
SWAP=`free -gh --si | tail -n 1 |awk {'print  $2'}`
SWAPUSED=`free -gh --si | tail -n 1 | awk {'print $3'}`
SWAPFREE=`free -gh --si | tail -n 1 | awk {'print $4'}`
SWAPPER=`free -gh --si | awk '/Swap/ { printf("%3.1f%%", $3/$2*100) }'`
LASTDAY=`lastlog -u geoff| tail -n 1| cut -d\  -f17`
LASTDATE=`lastlog -u geoff| tail -n 1| cut -d\  -f19`
LASTMONTH=`lastlog -u geoff| tail -n 1| cut -d\  -f18`
LASTTIME=`lastlog -u geoff| tail -n 1| cut -d\  -f20`
LASTYEAR=`lastlog -u geoff| tail -n 1| cut -d\  -f22`
LASTLOG="${LASTDAY} ${LASTYEAR}/${LASTMONTH}/${LASTDATE} ${LASTTIME} from "

# Gather Hardware Information
SDATEMP=`/usr/sbin/hddtemp -uf /dev/sda|cut -c 36-`
SDBTEMP=`/usr/sbin/hddtemp -uf /dev/sdb|cut -c 36-`
CPU=`cat /proc/cpuinfo | grep 'model name' | head -1 | cut -d':' -f2`

MEMPER2=`echo ${MEMPER} |cut -d. -f1`
SWAPPER2=`echo ${SWAPPER} |cut -d. -f1`
DISKPER2=`echo ${DISKPER}|cut -d% -f1`

if [ ${MEMPER2} -lt 75 ]; then
    MC=${GREEN}
elif [ ${MEMPER2} -ge 75 ] && [ ${MEMPER2} -lt 90 ]; then
    MC=${YELLOW}
else MC=${RED}
fi

if [ ${SWAPPER2} -lt 75 ]; then
    SC=${GREEN}
elif [ ${SWAPPER2} -ge 75 ] && [ ${SWAPPER2} -lt 90 ]; then
    SC=${YELLOW}
else SC=${RED}
fi

if [ ${DISKPER2} -lt 75 ]; then
    HC=${GREEN}
elif [ ${DISKPER2} -ge 75 ] && [ ${DISKPER2} -lt 90 ]; then
    HC=${YELLOW}
else HC=${RED}
fi

echo
echo "Distribution ..: ${DISTRIB_DESCRIPTION}"
echo "OS.............: ${KERNEL} ${OPERATING_SYSTEM}"
echo "Last Login.....: ${LASTLOG}"
echo "Uptime.........: ${UPTIME} Record: ${UPRECORDS}"
echo "Load...........: ${LOAD}"
echo "Memory.........: ${MC}${MEMORY} ${MEMUSED}/${MEMFREE} ${MEMPER}${DC}"
echo "Swap...........: ${SC}${SWAP} ${SWAPUSED}/${SWAPFREE} ${SWAPPER}${DC}"
echo "Disk Usage.....: ${HC}${DISK} ${DISKUSED}/${DISKFREE} ${DISKPER}${DC}"
echo "CPU............:${CPU}"
echo "Temperature....: CORE: MB: GPU: CPU:"
echo "Temperature....: SBA:${SDATEMP} SDB:${SDBTEMP}"
echo "Ext IP Address.: ${EXTIPADDR}  IP Address: ${IPADDR}"
echo "ISP............:${ISP}"
