#!/bin/sh

EXTIPADDR=`dig +short myip.opendns.com @resolver1.opendns.com`
CITY=`geoiplookup 108.81.26.10|grep City|cut -d, -f5`
STATE=`geoiplookup 108.81.26.10|grep City|cut -d, -f4`
ZIP=`geoiplookup ${EXTIPADDR}|grep City|cut -d, -f6`
TEMP=`weather ${ZIP}|grep Temp|cut -d: -f2`
TEMPCOLOR=`weather 30605|grep Temp|cut -d: -f2|cut -c 2-3`
HUMIDITY=`weather ${ZIP}|grep Rel|cut -d: -f2`
SKY=`weather ${ZIP}|grep Sky|cut -d: -f2`
WIND=`weather ${ZIP}|grep Wind|cut -d: -f2`

# Define Colors
    BLACK='\033[0;30m'
    GRAY='\033[1;30m'
    LIGHT_GRAY='\033[0;37m'
    WHITE='\033[1;37m'
    RED='\033[0;31m'
    LIGHT_RED='\033[1;31m'
    GREEN='\033[0;32m'
    LIGHT_GREEN='\033[1;32m'
    YELLOW='\033[0;33m'
    LIGHT_YELLOW="\033[1;33m"
    BLUE='\033[0;34m'
    LIGHT_BLUE='\033[1;34m'
    MAGENTA='\033[0;35m'
    LIGHT_MAGENTA='\033[1;35m'
    CYAN='\033[0;36m'
    LIGHT_CYAN='\033[1;36m'
    NO_COLOR='\033[0m'

    DC="${NO_COLOR}"

    SUPFREEZE="${LIGHT_CYAN}"
    FREEZE="${LIGHT_BLUE}"
    COLD="${BLUE}"
    CHILI="${GREEN}"
    NORMAL="${YELLOW}"
    HOT="${RED}"

    # Colour progression is important ... 
    # bold gray -> bold green -> bold yellow -> bold red -> 
    # black on red -> bold white on red 
    # 
    # Then we have to choose the values at which the colours switch, with 
    # anything past yellow being pretty important. 

    if [ ${TEMPCOLOR} -lt 0 ]; then 
	TC=$SUPFREEZE
    elif [ ${TEMPCOLOR} -ge 0 ] && [ ${TEMPCOLOR} -lt 33 ]; then 
        TC=${FREEZE}
    elif [ ${TEMPCOLOR} -ge 33 ] && [ ${TEMPCOLOR} -lt 50 ]; then 
	TC=${COLD}
    elif [ ${TEMPCOLOR} -ge 50 ] && [ ${TEMPCOLOR} -lt 65 ]; then 
	TC=${CHILI}
    elif [ ${TEMPCOLOR} -ge 65 ] && [ ${TEMPCOLOR} -lt 85 ]; then 
	TC=${NORMAL}
    else TC=${HOT}
    fi 

echo "Location.......:${CITY},${STATE}${ZIP}"
echo "Weather........:${TC}${TEMP}${DC} with ${SKY} skys and ${HUMIDITY} humidity."
